# Data Cleaning and Transformation
```{r}
library(forcats)
library(dplyr)
library(ggplot2)
library(devtools)
library(extracat)
library(stringr)
library(tidytext)
library(wordcloud2)
```

```{r}
df_ori <- read.csv('data/NYC_Jobs.csv')
head(df_ori)
```
# 3.2 Data Cleaning
```{r}
#select columns
df <- df_ori[,c('Agency', 'X..Of.Positions','Business.Title','Civil.Service.Title','Title.Classification','Level','Job.Category','Full.Time.Part.Time.indicator','Career.Level','Salary.Range.From','Salary.Range.To','Salary.Frequency','Division.Work.Unit','Minimum.Qual.Requirements','Preferred.Skills','Residency.Requirement','Work.Location')]
head(df)
```
```{r}
# Full time job
df <- df[df$Full.Time.Part.Time.indicator == 'F',]
# Entry Level Job
df <- df[df$Career.Level == 'Entry-Level',]
df <- df[ ,!(names(df) %in% c('Full.Time.Part.Time.indicator', 'Career.Level'))]
head(df)
```

# Data Transformation
```{r}
# find mean salary
df$mean.salary <- (df$Salary.Range.From + df$Salary.Range.To)/2

df <- df %>%
  mutate(res.requirement = case_when(
    grepl("not required", tolower(Residency.Requirement)) ~ 'not required',
    grepl("not currently required", tolower(Residency.Requirement)) ~ 'not required',
    grepl("no residency requirement", tolower(Residency.Requirement)) ~ 'not required',
    grepl("exempt from", tolower(Residency.Requirement)) ~ 'not required',
    grepl("generally required", tolower(Residency.Requirement)) ~ 'generally required',
    grepl("required within 90 days", tolower(Residency.Requirement)) ~ 'generally required',
    TRUE ~ 'required'
  ))
```
 
```{r}
#
#table(df$Minimum.Qual.Requirements)
#df <- df %>%
#  mutate(edu.require = case_when(
#    grepl('baccalaureate degree',Minimum.Qual.Requirements) ~ 'baccalaureate degree',
#    salary_type == 'week' ~ current_salary * 52,
#    TRUE ~ current_salary
#  ))
#table(df$Preferred.Skills)
```

# 3.3 Missing Value
```{r}
devtools::install_github("heike/extracat")
#colSums(is.na(df))
df <- df %>% mutate_all(na_if,"")
df_ori <- df_ori %>% mutate_all(na_if,"")
colMeans(is.na(df))*100
#visualize original df
extracat::visna(df_ori)
#visualize transformed df
extracat::visna(df)

```

```{r}
# Preferred.Skills
skill_miss <- subset(df,is.na(Preferred.Skills))
ggplot(skill_miss, aes(x=Agency)) +
  geom_bar()+
  theme(axis.text.x=element_text(angle=45,hjust=1),
        axis.text=element_text(size=5)) +
  labs(title="Missing Prefered Skill by Agency")
```
# 4 Results
```{r}
# Number of jobs by Agency
df_agency <- df %>%
  group_by(Agency) %>%
  summarise(Frequency = sum(X..Of.Positions))

ggplot(df_agency, aes(x = fct_reorder(Agency, Frequency,.desc = TRUE), y=Frequency))+
  geom_bar(stat='identity')  + 
  xlab("Agency")+
  ylab("Number of Jobs Posted") + 
  labs(title="Number of Jobs Posted by Agency")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=5.5),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```

```{r}
df_agency <- df %>%
  group_by(Agency) %>%
  summarise(Frequency = sum(X..Of.Positions))
df_agency <- df_agency %>%
  mutate(Agency =  
          case_when(Frequency <= 20 ~ "OTHER",
                    TRUE ~ Agency))
df_agency <- df_agency %>%
  group_by(Agency) %>%
  summarise(Frequency = sum(Frequency))
ggplot(df_agency, aes(x = fct_relevel(fct_reorder(Agency, Frequency,.desc = TRUE),"OTHER",after=Inf), y=Frequency))+
  geom_bar(stat='identity')  + 
  xlab("Agency")+
  ylab("Number of Jobs Posted") + 
  labs(title="Number of Jobs Posted by Agency")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=5.5),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```
```{r}
s_agency <- df %>%
  filter(Salary.Frequency == 'Annual') %>%
  group_by(Agency) %>%
  summarise(avgSalary = mean(mean.salary))
s_agency
ggplot(s_agency, aes(x = fct_reorder(Agency, avgSalary,.desc = TRUE), y=avgSalary))+
  geom_bar(stat='identity')  +
  xlab("Agency")+
  ylab("Average Salary") + 
  labs(title="Average Salary of Jobs Posted by Agency")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=5.5),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```

```{r}
# Cleveland dot plot of Average Salary
library(Lock5withR)
ggplot(s_agency, aes(x = avgSalary, y = fct_reorder(Agency, avgSalary))) +
  geom_point(color = "blue") +
  ggtitle("Average Annual Salary by Agency") +
  ylab("") +
  theme_linedraw()+
  theme(axis.text=element_text(size=5.5))
```


```{r}
# Job Category Cleaning
jobcat2 <- function(cat) {
  result <- c()
  if (length(cat)==0){
    return(result)
  }
  if (grepl(',', cat)){
    result <- strsplit(cat, ",")[[1]]
    for (i in 1:length(result)){
      if (substr(result[i],0,1) == ' '){
        result[i] = sub(" ","",result[i])
      }
      if (substr(result[i],0,2) == '& '){
        result[i] = sub("& ","",result[i])
      }
    }
  } else if (grepl('&',cat)){
    result <- strsplit(cat, "&")[[1]]
    for (i in 1:length(result)){
      if (substr(result[i],0,1) == ' '){
        result[i] = sub(" ","",result[i])
      }
    }
  } else {
   result <- c(result, cat)
  }
  return(result)
}

```

```{r}
# Extract first key word in category
extract_cat <- function(cat) {
  if (is.vector(cat)){
    result <- cat[[1]][1]
    if (grepl('&', result)){
      lst <- strsplit(cat, "&")[[1]]
      result <- lst[1]
    }
  }else{
      result <- cat[[1]]
    }
  return(result)
}

category_cleaned <- lapply(df$Job.Category, jobcat2)
category_cleaned <-unlist(lapply(category_cleaned, extract_cat))
```

```{r}
combine_cat <- function(cat) {
  if (grepl('Health', cat)){
    result <- 'Health'
  }else if (grepl('Legal Affairs', cat)){
    result <- 'Legal Affairs'
  } else if (grepl('Technology', cat)){
    result <- 'Technology'
  }else{
    result <- cat
  }
  return(result)
}

df$category_cleaned <- unlist(lapply(category_cleaned, combine_cat))
df %>%
  group_by(category_cleaned) %>%
  count()
```


```{r}
df_highs <- df %>%
  filter((Agency == "DEPT OF YOUTH & COMM DEV SRVS")|(Agency =="NYC EMPLOYEES RETIREMENT SYS")|(Agency == "DEPARTMENT OF TRANSPORTATION")) 
highsg <- df_highs %>%
  group_by(category_cleaned) %>%
  summarise(Frequency = sum(X..Of.Positions))
ggplot(highsg, aes(y = fct_reorder(category_cleaned, Frequency,.desc = FALSE), x=Frequency))+
  geom_bar(stat='identity')  +
  ylab("Job Category")+
  xlab("Number of Jobs Posted") + 
  labs(title="Number of Jobs by Job Category from Agencies with \nHigh Avg Salary")+
  theme(axis.text=element_text(size=8),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8),
        plot.title = element_text(size=10))
```


```{r}
#table(df$Job.Category)
```
```{r}
jobcat <- function(cat) {
  result <- c()
  if (length(cat)==0){
    return(result)
  }
  if (grepl(',',cat)){
    result <- strsplit(cat, ",")[[1]]
    for (i in 1:length(result)){
      if (substr(result[i],0,1) == ' '){
        result[i] = sub(" ","",result[i])
      }
      if (substr(result[i],0,2) == '& '){
        result[i] = sub("& ","",result[i])
      }
    }
  } else {
    result <- c()
    result[0] <- cat
  }
  return(result)
}
#df$catlst <-lapply(df$Job.Category, jobcat)
```

```{r}
df_jobcat <- df %>%
  group_by(category_cleaned) %>%
  summarise(Frequency = sum(X..Of.Positions))


ggplot(df_jobcat, aes(x = fct_reorder(category_cleaned, Frequency,.desc = TRUE), y=Frequency))+
  geom_bar(stat='identity')  + 
  xlab("Job Category")+
  ylab("Number of Jobs Posted") + 
  labs(title="Number of Jobs Posted by Job Category")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=7),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```


```{r}
# Cleveland dot plot of Average Salary
library(Lock5withR)

s_cat <- df %>%
  group_by(category_cleaned) %>%
  summarise(avgSalary = mean(mean.salary))

ggplot(s_cat, aes(x = avgSalary, y = fct_reorder(category_cleaned, avgSalary))) +
  geom_point(color = "blue") +
  ggtitle("Average Salary by Job Category") +
  ylab("") +
  theme_linedraw()
```


```{r}
# avg salary by job category
s_cat <- df %>%
  group_by(category_cleaned) %>%
  summarise(avgSalary = mean(mean.salary))


ggplot(s_cat, aes(x = fct_reorder(category_cleaned, avgSalary,.desc = TRUE), y=avgSalary))+
  geom_bar(stat='identity')  +
  xlab("Job Cateogry")+
  ylab("Average Salary") + 
  labs(title="Average Salary by Job Category")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=5.5),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```
```{r}
annual_salary <- df %>%
  filter(Salary.Frequency == 'Annual') 

ggplot(annual_salary, aes(x=reorder(category_cleaned, -mean.salary, median),y=mean.salary)) +
  geom_boxplot() +
  coord_flip() +
  ggtitle("Boxplot of Mean Annual Salary by Job Category") +
  labs(y="Mean Annnual Salary", x="Job Category") +
  theme(plot.title = element_text(size=12))
```
```{r}
# Qual Requirements Cleaning
extract_qual <- function(qual) {
  qual <- tolower(qual)
  if (grepl('master', qual)){
    result <- 'master degree'
  }else if (grepl('college', qual) | grepl('law school', qual)){
    result <- 'college degree'
  }else if (grepl('high school', qual)){
    result <- 'high school'
  }else if (grepl('certificate', qual) | grepl('possess', qual)){
    result <- 'relevant certificates required'
  }else if (grepl('experience', qual)){
    result <- 'relative experience required'
  }else if (grepl('ability', qual)){
    result <- 'special abilities required'
  }else if (grepl('no formal', qual)){
    result <- 'no formal requirements'
  }else{
    result <- qual
  }
  return(result)
}
```
```{r}
df$minqual_cleaned <- unlist(lapply(df$Minimum.Qual.Requirements, extract_qual))

df %>%
  group_by(minqual_cleaned) %>%
  count()
```

```{r}
# competitiveness vs. master qualification
df %>%
  group_by(Title.Classification) %>%
  count()

df_comp <- df %>%
  filter((Title.Classification == 'Competitive-1') | (Title.Classification == 'Non-Competitive-5')) %>%
  mutate(competitiveness = case_when(
    grepl("Non-Competitive-5", Title.Classification) ~ 'not competitive',
    TRUE ~ 'highly competitive'
  ))

df_ms <- df_comp %>%
  mutate(master_qual = case_when(
    grepl("master", minqual_cleaned) ~ 'master required',
    TRUE ~ 'master not required'
  ))

counts2 <- df_ms%>%
  group_by(competitiveness, master_qual)%>%
  summarise(Freq = sum(mean.salary))

vcd::mosaic(competitiveness ~ master_qual, counts2, direction = c("v", "h"))
```

```{r}

annual_salary <- df %>%
  filter(Salary.Frequency == 'Annual') %>%
  filter((minqual_cleaned != 'special abilities required') & (!is.na(minqual_cleaned)))

p <- ggplot(annual_salary, aes( mean.salary, factor(minqual_cleaned)))
p + geom_violin() +
  ggtitle("Violin Plot of Mean Annual Salary by Minimum Qualification Requirement") +
  labs(x="Mean Annnual Salary", y="Min Qualification Requirement") +
  theme(plot.title = element_text(size=12))
```
#Skill
```{r}
#clean skill
df$cleanskill <- tolower(lapply(df$Preferred.Skills,function(x) str_replace_all(x, "[^a-zA-Z]", " ")))
df_skill <- df  %>%
  unnest_tokens(cleanskill, cleanskill) %>%
  anti_join(stop_words, by= c("cleanskill" = "word"))
skills <- names(sort(table(df_skill$cleanskill),decreasing=TRUE)[1:50])
common <- c("skills","ability","experience","excellent","strong","knowledge","proficiency","demonstrated","including","deadlines","preferred","detail","people","attention","weekends","city", "independently","multiple","effectively","qualifications","service","candidate","familiarity","candidates")
skillset <- skills[!skills %in% common]
df_skill <- df_skill %>%
  filter(cleanskill %in% skillset)
```

```{r}
#graph
gskill <- df_skill %>%
  group_by(cleanskill) %>% 
  summarise(Freq = sum(X..Of.Positions),avgSalary = mean(mean.salary))
ggplot(gskill, aes(x = fct_reorder(cleanskill, Freq,.desc = TRUE), y=Freq))+
  geom_bar(stat='identity')  + 
  xlab("Skill")+
  ylab("Number of Jobs Related") + 
  labs(title="Skill Freq Distribution")+
  theme(axis.text.x=element_text(angle=60,hjust=1),
        axis.text=element_text(size=5.5),
        axis.title.x = element_text(size=8),
        axis.title.y = element_text(size=8))
```
```{r}
ggplot(gskill, aes(x = avgSalary, y = fct_reorder(cleanskill, avgSalary))) +
  geom_point(color = "blue") +
  ggtitle("Avg Salary of Jobs Related to Skill") +
  ylab("AvgSalary") +
  theme_linedraw()+
  theme(axis.text=element_text(size=5.5))
```


```{r}
techskill <- df_skill %>%
  filter(category_cleaned == "Technology") %>%
  group_by(cleanskill) %>%
  summarise(Freq=sum(X..Of.Positions))
wordcloud2(techskill)
```
```{r}
buildskill <- df_skill %>%
  filter(category_cleaned == "Building Operations ") %>%
  group_by(cleanskill) %>%
  summarise(Freq=sum(X..Of.Positions))
wordcloud2(buildskill)
```

