--- 
title: "EDAV Final Project - NYC Jobs"
author: "Jackie Feng, Yuqian Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
New York City is the most populous city in the United States and is often described as the most powerful global city. It has significant impacts on commerce, finance, media, art, technology, education, entertainment, etc. The abundant opportunities provided here attract millions of people to pursue their dream and a better life. Among those working opportunities, the jobs posted by the NYC government official is definitely one of the most attractive ones for their reliability, stability, and satisfying salary. That is why we are interested in the jobs posted on City of New York’s official jobs site.

In this project, we are going to research the factors that influence the salaries of jobs in NYC government. In particular, we want to study the salaries of entry level jobs to see if business titles, job categories, agency and divisions, education backgrounds, etc. have impacts on the salaries. The result of this project could serve as a reference to college students and new graduates who want to find a job in NYC government and fulfilling their dreams in NYC.

