# Proposal

## Research topic
 We want to study the job conditions in NYC. One of the most important aspects we would study is the influential factors of the salaries of jobs. We did the study based on the current job postings available on the City of New York’s official jobs site reported by the NYC government. We would narrow down our focus to entry level, full-time jobs, as what we concern the most as future new graduate students, to see if titles, job categories, agency and divisions, education backgrounds, etc. are related to the salaries of jobs. Besides the influential factors of the salary, we would further study job conditions in NYC from different aspects, for example, what are the basic qualifications and skills for jobs in different agencies, which areas have the most opportunities for job seekers, and how do salaries vary from different regions, etc. 

## Data availability
 The data we use in this project is from NYC Open Data (https://opendata.cityofnewyork.us). It is managed by the Open Data Team at the NYC Office of Technology and Innovation (OTI) and it contains free public data published by New York City agencies and other partners.
 
 The ataset we use is *NYC Jobs* (https://data.cityofnewyork.us/City-Government/NYC-Jobs/kpav-sd4t) from this website. It contains current job postings available on the City of New York’s official jobs site (http://www.nyc.gov/html/careers/html/search/search.shtml). The data includes internal postings available to city employees and external postings available to the general public. The data is provided by Department of Citywide Administrative Services (DCAS). The data is constantly updating. It is updated "as needed" automatically. It was initially made public on May, 2013, and the last updated date as we worked on this project is on December 6, 2022.
 
 The data is presented as a table on the website. We downloaded the data by exporting it to a CSV file directly from the website. To use it in our project, we would import the data using *read.csv()* function in R to read in and save the data set as a DataFrame object. The DataFrame contains 5421 observations and 30 variables. Each row is a job posting on the website, and the columns are the information for each job, eg. Agency, Business Title, Career Level, Salary, Job Category, Minimum Qual Requirements etc. As some columns contain tedious information and verbose texts that are irrelevant to our project, we wound mainly focus on some selected columns that are related with our study and provide insights on the job conditions in this project.

 The data is tidy since each row in the data set represents a single job posting with a unique job ID. It contains missing values on many columns and we would address the missing values on columns that are related to our study. After further explorations, we found the missing values on columns have some patterns, so we would also study if the missing patterns suggest something meaningful to the job conditions.


